Repository FederatedAI/FATE-Client, pull requests merged in 2023-06, with the labels that each got.

#8 add stat (#4663)
  python/fate_client/pipeline/component_define/fate/statistics.yaml
  python/fate_client/pipeline/components/fate/__init__.py
  python/fate_client/pipeline/components/fate/statistics.py
Labels: enhancement

#9 add scale with minmax & standard method (#4670)
  python/fate_client/pipeline/component_define/fate/feature_scale.yaml
  python/fate_client/pipeline/components/fate/feature_scale.py
Labels: enhancement

#12 pipeline update: adjust flow sdk call
  python/fate_client/pipeline/component_define/fate/dataframe_io_test.yaml
  python/fate_client/pipeline/components/fate/__init__.py
  python/fate_client/pipeline/components/fate/dataframe_io_test.py
  python/fate_client/pipeline/executor/task_executor.py
  python/fate_client/pipeline/pipeline.py
  python/fate_client/pipeline/utils/fateflow/fate_flow_job_invoker.py
Labels: enhancement

#13 fix bug: change component artifact: type to types list
  python/fate_client/pipeline/component_define/fate/dataframe_io_test.yaml
  python/fate_client/pipeline/component_define/fate/dataframe_transformer.yaml
  python/fate_client/pipeline/entity/component_structures.py
Labels: bug

#14 fix dag generating: if key type is_multi but input is single artifact
  python/fate_client/pipeline/components/component_base.py
Labels: bug

#15 Bug-Fix
  python/fate_client/pipeline/components/component_base.py
  python/fate_client/pipeline/entity/dag_structures.py
Labels: bug, enhancement

#16 api fix: fix output model and metric
  python/fate_client/pipeline/entity/task_info.py
  python/fate_client/pipeline/pipeline.py
  python/fate_client/pipeline/utils/fateflow/fate_flow_job_invoker.py
Labels: enhancement

#18 pipeline: support get component output data from fate_flow
  python/fate_client/pipeline/entity/task_info.py
  python/fate_client/pipeline/utils/fateflow/fate_flow_job_invoker.py
Labels: enhancement

#22 fix deploy logic
  python/fate_client/pipeline/pipeline.py
Labels: bug
