Repository FederatedAI/FATE-Client, pull requests merged in 2023-09, with the labels that each got.

#82 Feature 2.0.0 beta Update
  python/fate_client/__init__.py
  python/fate_client/pipeline/__init__.py
  python/fate_client/pipeline/components/component_base.py
  python/fate_client/pipeline/conf/env_config.py
  python/fate_client/pipeline/conf/types.py
  python/fate_client/pipeline/entity/__init__.py
  python/fate_client/pipeline/entity/dag.py
  python/fate_client/pipeline/entity/model_info.py
  python/fate_client/pipeline/entity/task_info.py
  python/fate_client/pipeline/entity/task_structure.py
  python/fate_client/pipeline/executor/__init__.py
  python/fate_client/pipeline/executor/task_executor.py
  python/fate_client/pipeline/manager/__init__.py
  python/fate_client/pipeline/manager/data_manager.py
  python/fate_client/pipeline/manager/metric_manager.py
  python/fate_client/pipeline/manager/model_manager.py
  python/fate_client/pipeline/manager/resource_manager.py
  python/fate_client/pipeline/manager/status_manager.py
  python/fate_client/pipeline/manager/task_conf_manager.py
  python/fate_client/pipeline/pipeline.py
  python/fate_client/pipeline/pipeline_config.yaml
  python/fate_client/pipeline/scheduler/component_stage.py
  python/fate_client/pipeline/scheduler/dag_parser.py
  python/fate_client/pipeline/scheduler/runtime_constructor.py
  python/fate_client/pipeline/utils/file_utils.py
  python/fate_client/pipeline/utils/standalone/__init__.py
  python/fate_client/pipeline/utils/standalone/id_gen.py
  python/fate_client/pipeline/utils/standalone/job_process.py
  python/fate_client/pipeline/utils/test_utils.py
  python/fate_client/pipeline/utils/uri_tools.py
  python/setup.py
Labels: enhancement

#84 pipeline: update job parameter define
  python/fate_client/pipeline/entity/dag_structures.py
Labels: enhancement

#87 use new distributed histogram api in hetero feature binning (#4660)
  python/fate_client/pipeline/component_define/fate/hetero_feature_binning.yaml
  python/fate_client/pipeline/components/fate/hetero_feature_binning.py
  python/fate_client/pipeline/utils/test_utils.py
Labels: enhancement

#89 fix woe computation(#4660)
  doc/pipeline.md
  python/fate_client/pipeline/utils/fateflow/fate_flow_job_invoker.py
Labels: documentation

#90 pipeline: add sitename
  python/fate_client/pipeline/pipeline.py
  python/fate_client/pipeline/utils/fateflow/fate_flow_job_invoker.py
Labels: enhancement

#92 pipeline fix
  python/fate_client/pipeline/pipeline.py
Labels: bug

#93 update description file
  python/fate_client/pipeline/component_define/fate/data_split.yaml
  python/fate_client/pipeline/component_define/fate/dataframe_io_test.yaml
  python/fate_client/pipeline/component_define/fate/dataframe_transformer.yaml
  python/fate_client/pipeline/component_define/fate/evaluation.yaml
  python/fate_client/pipeline/component_define/fate/feature_scale.yaml
  python/fate_client/pipeline/component_define/fate/hetero_feature_selection.yaml
  python/fate_client/pipeline/component_define/fate/hetero_sbt.yaml
  python/fate_client/pipeline/component_define/fate/homo_lr.yaml
  python/fate_client/pipeline/component_define/fate/homo_nn.yaml
  python/fate_client/pipeline/component_define/fate/psi.yaml
  python/fate_client/pipeline/component_define/fate/reader.yaml
  python/fate_client/pipeline/component_define/fate/sample.yaml
  python/fate_client/pipeline/component_define/fate/statistics.yaml
  python/fate_client/pipeline/component_define/fate/union.yaml
Labels: enhancement

#94 Dev 2.0.0 import fix
  python/fate_client/pipeline/component_define/fate/hetero_sbt.yaml
  python/fate_client/pipeline/components/fate/hetero_sbt.py
  python/fate_client/pipeline/components/fate/homo_nn.py
  python/fate_client/pipeline/components/fate/nn/patched_torch/base.py
  python/fate_client/pipeline/components/fate/nn/patched_torch/nn.py
  python/fate_client/pipeline/components/fate/nn/patched_torch/optim.py
Labels: enhancement

#95 add sitename to flow executor
  python/fate_client/pipeline/executor/task_executor.py
Labels: enhancement

#101 Dev 2.0.0 import fix
  python/fate_client/pipeline/components/fate/__init__.py
  python/fate_client/pipeline/components/fate/coordinated_linr.py
  python/fate_client/pipeline/components/fate/coordinated_lr.py
  python/fate_client/pipeline/components/fate/data_split.py
  python/fate_client/pipeline/components/fate/dataframe_io_test.py
  python/fate_client/pipeline/components/fate/dataframe_transformer.py
  python/fate_client/pipeline/components/fate/evaluation.py
  python/fate_client/pipeline/components/fate/feature_scale.py
  python/fate_client/pipeline/components/fate/hetero_feature_binning.py
  python/fate_client/pipeline/components/fate/hetero_feature_selection.py
  python/fate_client/pipeline/components/fate/hetero_sbt.py
  python/fate_client/pipeline/components/fate/homo_lr.py
  python/fate_client/pipeline/components/fate/homo_nn.py
  python/fate_client/pipeline/components/fate/nn/__init__.py
  python/fate_client/pipeline/components/fate/nn/algo_params.py
  python/fate_client/pipeline/components/fate/nn/loader.py
  python/fate_client/pipeline/components/fate/nn/patched_torch/nn.py
  python/fate_client/pipeline/components/fate/nn/torch/__init__.py
  python/fate_client/pipeline/components/fate/nn/torch/base.py
  python/fate_client/pipeline/components/fate/nn/torch/nn.py
  python/fate_client/pipeline/components/fate/nn/torch/optim.py
  python/fate_client/pipeline/components/fate/psi.py
  python/fate_client/pipeline/components/fate/reader.py
  python/fate_client/pipeline/components/fate/sample.py
  python/fate_client/pipeline/components/fate/statistics.py
  python/fate_client/pipeline/components/fate/union.py
Labels: bug, enhancement

#100 pipeline: update cli, edit dag entity
  python/fate_client/pipeline/entity/dag_structures.py
  python/fate_client/pipeline/pipeline_cli.py
Labels: enhancement

#103 update requirements
  python/requirements.txt
  python/setup.py
Labels: documentation

#104 update readme and release note
  README.md
  RELEASE.md
Labels: documentation

#106 fix import
  python/fate_client/pipeline/components/fate/__init__.py
Labels: bug

#107 fix statistic filter param(#4661)
  python/fate_client/pipeline/component_define/fate/hetero_feature_selection.yaml
Labels: enhancement
