Repository FederatedAI/FATE-Client, pull requests merged in 2023-07, with the labels that each got.

#25 dag_parser: fix model key infer when deploying
  python/fate_client/pipeline/scheduler/dag_parser.py
Labels: bug

#29 dag_parser: bug-fix, support party task global conf
  python/fate_client/pipeline/components/component_base.py
  python/fate_client/pipeline/entity/dag_structures.py
  python/fate_client/pipeline/pipeline.py
  python/fate_client/pipeline/scheduler/dag_parser.py
Labels: bug, enhancement

#32 add cross_validation to stages
  python/fate_client/pipeline/conf/types.py
  python/fate_client/pipeline/entity/dag_structures.py
Labels: enhancement

#33 Pipeline Bug-Fix
  python/fate_client/pipeline/pipeline.py
Labels: bug

#34 Feature 2.0.0 selection
  python/fate_client/pipeline/component_define/fate/hetero_feature_selection.yaml
  python/fate_client/pipeline/components/fate/hetero_feature_selection.py
Labels: bug

#35 Pipeline Bug Fix
  python/fate_client/pipeline/pipeline.py
Labels: bug

#37 Feature 2.0.0 selection
  python/fate_client/pipeline/component_define/fate/coordinated_linr.yaml
  python/fate_client/pipeline/component_define/fate/coordinated_lr.yaml
  python/fate_client/pipeline/components/fate/coordinated_linr.py
  python/fate_client/pipeline/components/fate/coordinated_lr.py
Labels: enhancement

#36 Pipeline DataFrameTransformer Calling Interface Adjust
  python/fate_client/pipeline/executor/task_executor.py
  python/fate_client/pipeline/utils/fateflow/fate_flow_job_invoker.py
Labels: bug

#40 Update Homo config
  python/fate_client/pipeline/component_define/fate/evaluation.yaml
  python/fate_client/pipeline/component_define/fate/homo_lr.yaml
  python/fate_client/pipeline/component_define/fate/homo_nn.yaml
  python/fate_client/pipeline/components/fate/evaluation.py
  python/fate_client/pipeline/components/fate/homo_lr.py
Labels: enhancement

#39 make output cv data optional(#4659)
  python/fate_client/pipeline/component_define/fate/coordinated_linr.yaml
  python/fate_client/pipeline/component_define/fate/coordinated_lr.yaml
  python/fate_client/pipeline/components/fate/coordinated_linr.py
  python/fate_client/pipeline/components/fate/coordinated_lr.py
Labels: enhancement

#42 coordinated lr & linr support warm start(#4659)
  python/fate_client/pipeline/component_define/fate/coordinated_linr.yaml
  python/fate_client/pipeline/component_define/fate/coordinated_lr.yaml
  python/fate_client/pipeline/components/fate/coordinated_linr.py
  python/fate_client/pipeline/components/fate/coordinated_lr.py
Labels: enhancement

#44 Pipeline Update
  python/fate_client/pipeline/conf/env_config.py
  python/fate_client/pipeline/pipeline.py
  python/fate_client/pipeline/utils/fateflow/fate_flow_job_invoker.py
Labels: bug, enhancement

#47 fix bug & update args
  python/fate_client/flow_cli/commands/job.py
  python/fate_client/flow_cli/commands/output.py
  python/fate_client/flow_cli/commands/permission.py
  python/fate_client/flow_cli/commands/task.py
  python/fate_client/flow_cli/utils/cli_args.py
  python/fate_client/flow_sdk/api/data.py
  python/fate_client/flow_sdk/api/output.py
Labels: bug, enhancement

#48 pipeline: adjust for flow_sdk download interface
  python/fate_client/pipeline/utils/fateflow/fate_flow_job_invoker.py
Labels: enhancement

#49 Feature 2.0.0 selection
  python/fate_client/pipeline/component_define/fate/hetero_feature_binning.yaml
  python/fate_client/pipeline/component_define/fate/sample.yaml
  python/fate_client/pipeline/components/fate/__init__.py
  python/fate_client/pipeline/components/fate/hetero_feature_binning.py
  python/fate_client/pipeline/components/fate/sample.py
Labels: enhancement

#50 Feature 2.0.0 selection
  python/fate_client/pipeline/component_define/fate/data_split.yaml
  python/fate_client/pipeline/component_define/fate/feature_union.yaml
  python/fate_client/pipeline/components/fate/__init__.py
  python/fate_client/pipeline/components/fate/data_split.py
  python/fate_client/pipeline/components/fate/feature_union.py
Labels: enhancement

#51 Feature 2.0.0 sample
  python/fate_client/pipeline/component_define/fate/data_split.yaml
  python/fate_client/pipeline/component_define/fate/sample.yaml
  python/fate_client/pipeline/components/fate/__init__.py
  python/fate_client/pipeline/components/fate/data_split.py
  python/fate_client/pipeline/components/fate/sample.py
Labels: enhancement

#52 rename param for data split (#4779)
  python/fate_client/pipeline/component_define/fate/data_split.yaml
  python/fate_client/pipeline/component_define/fate/sample.yaml
  python/fate_client/pipeline/components/fate/data_split.py
  python/fate_client/pipeline/components/fate/sample.py
Labels: enhancement

#53 add param check for 'transform_method'(#4660)
  python/fate_client/pipeline/component_define/fate/hetero_feature_binning.yaml
Labels: enhancement

#55 edit sample check & fix federated sample(#4662)
  python/fate_client/pipeline/component_define/fate/sample.yaml
  python/fate_client/pipeline/components/fate/sample.py
Labels: enhancement

#56 rename union & add schema check(#4668)
  python/fate_client/pipeline/component_define/fate/union.yaml
  python/fate_client/pipeline/components/fate/__init__.py
  python/fate_client/pipeline/components/fate/union.py
Labels: enhancement
