Repository FederatedAI/FATE-Client, pull requests merged in 2023-12, with the labels that each got.

#113 add pearson client cpn
  python/fate_client/pipeline/component_define/fate/feature_correlation.yaml
  python/fate_client/pipeline/component_define/fate/sshe_linr.yaml
  python/fate_client/pipeline/component_define/fate/sshe_lr.yaml
  python/fate_client/pipeline/components/fate/__init__.py
  python/fate_client/pipeline/components/fate/feature_correlation.py
  python/fate_client/pipeline/components/fate/sshe_linr.py
  python/fate_client/pipeline/components/fate/sshe_lr.py
Labels: enhancement

#117 Fix bugs
  python/fate_client/pipeline/components/fate/hetero_secureboost.py
Labels: bug

#119 always turn off reveal every epoch for SSHE LR & LinR(#5227)
  python/fate_client/pipeline/components/fate/sshe_linr.py
  python/fate_client/pipeline/components/fate/sshe_lr.py
Labels: enhancement

#122 PipeLine Bug Fix
  python/fate_client/pipeline/scheduler/dag_parser.py
Labels: bug

#123 pipeline: support pipeline party conf
  python/fate_client/pipeline/entity/dag.py
  python/fate_client/pipeline/pipeline.py
Labels: enhancement

#124 Pipeline Buf Fix
  python/fate_client/pipeline/adapters/bfia/translator/dsl_translator.py
  python/fate_client/pipeline/entity/dag_structures.py
  python/fate_client/pipeline/entity/runtime_entity.py
  python/fate_client/pipeline/executor/task_executor.py
  python/fate_client/pipeline/pipeline.py
  python/fate_client/pipeline/scheduler/dag_parser.py
  python/fate_client/pipeline/utils/fateflow/fate_flow_job_invoker.py
Labels: bug

#125 Feature 2.0.0 rc dag translate
  python/fate_client/pipeline/adapters/__init__.py
  python/fate_client/pipeline/adapters/bfia/component_define/unionpay/hetero_secureboost.yaml
  python/fate_client/pipeline/adapters/bfia/component_define/unionpay/intersection.yaml
  python/fate_client/pipeline/adapters/bfia/components/unionpay/hetero_lr.py
  python/fate_client/pipeline/adapters/bfia/components/unionpay/hetero_secureboost.py
  python/fate_client/pipeline/adapters/bfia/components/unionpay/intersection.py
  python/fate_client/pipeline/adapters/bfia/translator/dag_spec.py
  python/fate_client/pipeline/adapters/bfia/translator/dsl_translator.py
  python/fate_client/pipeline/components/component_base.py
  python/fate_client/pipeline/entity/dag.py
  python/fate_client/pipeline/entity/dag_structures.py
  python/fate_client/pipeline/interface/channel.py
  python/fate_client/pipeline/pipeline.py
  python/fate_client/pipeline/scheduler/dag_parser.py
Labels: bug, enhancement

#127 Dev 2.0.0 rc nn update
  python/fate_client/pipeline/component_define/fate/hetero_nn.yaml
  python/fate_client/pipeline/component_define/fate/homo_nn.yaml
  python/fate_client/pipeline/components/fate/hetero_nn.py
  python/fate_client/pipeline/components/fate/nn/algo_params.py
Labels: enhancement

#129 Feature 2.0.0 rc pearson
  python/fate_client/pipeline/component_define/fate/coordinated_linr.yaml
  python/fate_client/pipeline/component_define/fate/coordinated_lr.yaml
  python/fate_client/pipeline/component_define/fate/data_split.yaml
  python/fate_client/pipeline/component_define/fate/feature_correlation.yaml
  python/fate_client/pipeline/component_define/fate/feature_scale.yaml
  python/fate_client/pipeline/component_define/fate/hetero_feature_binning.yaml
  python/fate_client/pipeline/component_define/fate/hetero_feature_selection.yaml
  python/fate_client/pipeline/component_define/fate/psi.yaml
  python/fate_client/pipeline/component_define/fate/sample.yaml
  python/fate_client/pipeline/component_define/fate/sshe_linr.yaml
  python/fate_client/pipeline/component_define/fate/sshe_lr.yaml
  python/fate_client/pipeline/component_define/fate/statistics.yaml
  python/fate_client/pipeline/component_define/fate/union.yaml
Labels: enhancement

#130 Feature 2.0.0 rc dag translate
  python/fate_client/pipeline/adapters/bfia/translator/dsl_translator.py
  python/fate_client/pipeline/scheduler/dag_parser.py
Labels: bug, enhancement

#131 pipeline: add engine to bfia components
  python/fate_client/pipeline/adapters/bfia/component_define/unionpay/hetero_lr.yaml
  python/fate_client/pipeline/adapters/bfia/component_define/unionpay/hetero_secureboost.yaml
  python/fate_client/pipeline/adapters/bfia/component_define/unionpay/intersection.yaml
  python/fate_client/pipeline/adapters/bfia/components/unionpay/hetero_lr.py
  python/fate_client/pipeline/adapters/bfia/components/unionpay/hetero_secureboost.py
  python/fate_client/pipeline/adapters/bfia/components/unionpay/intersection.py
Labels: enhancement

#134 Feature 2.0.0 rc pearson
  python/fate_client/pipeline/component_define/fate/evaluation.yaml
  python/fate_client/pipeline/component_define/fate/hetero_nn.yaml
  python/fate_client/pipeline/component_define/fate/hetero_sbt.yaml
  python/fate_client/pipeline/component_define/fate/homo_nn.yaml
  python/fate_client/pipeline/component_define/fate/reader.yaml
Labels: enhancement

#138 Dev 2.0.0 rc nn update
  python/fate_client/pipeline/component_define/fate/homo_lr.yaml
Labels: enhancement

#139 update yaml, delete unused cpns
  python/fate_client/__init__.py
  python/fate_client/pipeline/component_define/fate/dataframe_io_test.yaml
  python/fate_client/pipeline/component_define/fate/dataframe_transformer.yaml
  python/fate_client/pipeline/components/fate/__init__.py
  python/fate_client/pipeline/components/fate/dataframe_io_test.py
  python/fate_client/pipeline/entity/dag.py
Labels: documentation, enhancement

#143 Update cli doc
  README.md
  doc/cli_index.md
  doc/pipeline.md
Labels: documentation
