Repository FederatedAI/FATE-Client, pull requests merged in 2024-02, with the labels that each got.

#146 Feature 2.1.0 support llm
  python/MANIFEST.in
  python/fate_client/pipeline/components/fate/homo_nn.py
  python/fate_client/pipeline/components/fate/nn/algo_params.py
  python/fate_client/pipeline/components/fate/nn/common_utils.py
Labels: enhancement

#148 rename union input: input data list --> input datas
  python/fate_client/pipeline/component_define/fate/union.yaml
  python/fate_client/pipeline/components/fate/union.py
Labels: documentation, enhancement

#149 edit doc
  doc/pipeline.md
Labels: documentation

#150 edit load config
  python/fate_client/pipeline/utils/test_utils.py
Labels: enhancement
